SkillProfi.Web/Controllers/ITServiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi.DAL.Models;
using SkillProfi.Web.Interfaces;
using SkillProfi.Web.ViewModels;

namespace SkillProfi.Web.Controllers
{
    [Authorize]
    public class ITServiceController : Controller
    {
        private IData<Request> _requestData;
        private IEnumerable<string> statuses = new List<string>()
            {
                new string("Получена"),
                new string ("В работе"),
                new string ("Выполнена"),
                new string ("Отклонена"),
                new string ("Отменена")
            };

        public int PageSize = 10;

        public ITServiceController(IData<Request> requestData)
        {
            _requestData = requestData;
        }

        public async Task<IActionResult> Index(string status, int requestPage = 1)
        {
            ViewData["Title"] = "IT Service";

            IEnumerable<Request> requests;

            if (string.IsNullOrEmpty(status)) // если статус не задан
            {
                requests = await _requestData.GetAll(); // получаем все заявки
            }
            else
            {
                // иначе получаем заявки, согласно заданному статусу
                requests = (await _requestData.GetAll()).Where(p => p.Status == status);
            }

            return View(new RequestsListViewModel
            {
                Requests = (requests)
                        .Skip((requestPage - 1) * PageSize) // пропускаем заявки до текущей страницы
                        .Take(PageSize), 
                PagingInfo = new PagingInfo
                {
                    CurrentPage = requestPage,
                    ItemsPerPage = PageSize,
                    TotalItems = status == null ?
                        requests.Count() :
                        requests.Where(e => e.Status == status).Count()
                },
                CurrentStatus = status
            });
        }

        [HttpGet("Requests/{id:int}")]
        public async Task<IActionResult> Details(int id)
        {
            ViewBag.Statuses = statuses;
            var request = await _requestData.GetById(id);
            ViewData["Title"] = $"IT Service - Заявка #{id}";

            return View(request);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Request request)
        {
            await _requestData.Update(request);

            return RedirectToAction("Index");
        }
    }
}

SkillProfi.Web/ViewComponent/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace SkillProfi.Web.Component
{
    /// <summary>
    /// На странице IT Service добавляет список фильтров.
    /// </summary>
    public class NavigationMenuViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedStatus = RouteData?.Values["status"];
            ViewData["selected_status"] = RouteData?.Values["status"];
            return View(new[]
            {
                new string("Получена"),
                new string ("В работе"),
                new string ("Выполнена"),
                new string ("Отклонена"),
                new string ("Отменена")
            });
        }
    }
}

SkillProfi.Web/Views/ITService/Details.cshtml
@model SkillProfi.DAL.Models.Request

<form method="post" asp-action="Edit">
    <div>
        <h4>Заявка</h4>
        <hr />

            <dl class="attrs">
                <dt>
                    @Html.DisplayNameFor(model => model.Id)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Id)
                    <input asp-for="@Model.Id" hidden />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Created)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Created)
                    <input asp-for="@Model.Created" hidden />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Name)
                    <input asp-for="@Model.Name" hidden />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Message)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Message)
                    <input asp-for="@Model.Message" hidden />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Status)
                </dt>
                <dd>
                    <select asp-for="@Model.Status">
                        @foreach(var opt in ViewBag.Statuses)
                        {
                            if (opt.Equals(Model.Status))
                            {
                                <option value="@opt" selected disabled>@opt</option>
                            }
                            else
                            {
                                <option value="@opt">@opt</option>
                            }
                        }
                    </select>
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Email)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Email)
                    <input asp-for="@Model.Email" hidden />
                </dd>
            </dl>
    </div>
    <div>
        <button class="r__btn request__edit btn btn__reset" type="submit">
            Изменить
        </button>
        <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
    </div>
</form>

SkillProfi.Web/Views/ITService/Index.cshtml
@model RequestsListViewModel

<section class="section itservice">
    <p class="count__requests">
        Всего заявок: @Model.PagingInfo.TotalItems
    </p>

    <div class="navigation-menu">
        <vc:navigation-menu />
    </div>

    <table class="table">
        <thead>
            <tr>
                <th class="table__id">
                    Номер заявки
                </th>
                <th class="table__created">
                    Заявка получена
                </th>
                <th class="table__name">
                    Имя
                </th>
                <th class="table__msg">
                    Описание
                </th>
                <th class="table__contacts">
                    Контакты
                </th>
                <th class="table__status">
                    Статус
                </th>
                <th class="table__action">
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Requests)
            {
                <tr>
                    <td class="table__id">
                        @item.Id
                    </td>
                    <td class="table__created">
                        @item.Created.ToString("dd.MM.yy HH:mm")
                    </td>
                    <td class="table__name">
                        @item.Name
                    </td>
                    <td class="table__msg">
                        @item.Message
                    </td>
                    <td class="table__contacts">
                        @item.Email
                    </td>
                    <td class="table__status">
                        @item.Status
                    </td>
                    <td class="table__action">
                        <a class="r__btn request__details btn btn__reset"
                           asp-action="Details"
                           asp-route-id="@item.Id">
                            Детали
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <div class="paging__search__block">
        <div page-model="@Model.PagingInfo" page-action="Index"
             page-classed-enabled="true"
             page-class="btn" page-class-normal="btn-blue"
             page-class-selected="btn-blue-selected"
             page-url-status="@Model.CurrentStatus"
             class="paging-info btn-group pull-right">
        </div>

        <div page-model-search="@Model.CurrentStatus">

        </div>
    </div>
</section>