SkillProfi.Web/Controllers/HeroController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi.DAL.Models;
using SkillProfi.DAL.SiteConfiguration;
using SkillProfi.Web.Interfaces;
using SkillProfi.Web.ViewModels;

namespace SkillProfi.Web.Controllers
{
    public class HeroController : Controller
    {
        private IData<Request> _requestData;
        private static string status;

        public HeroController(IData<Request> requestData)
        {
            _requestData = requestData;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(Request request)
        {
            if (ModelState.IsValid)
            {
                request.Status = "Получена";
                request.Created = DateTime.Now;
                _requestData.Add(request);
                status = "Заявка успешно отправлена!";
            }
            else
            {
                status = "Некорректно заполнены данные!";
            }

            return RedirectToAction("RequestSent");
        }

        [HttpGet]
        public IActionResult RequestSent()
        {
            ViewData["Title"] = "SkillProfi";

            return View((object)status);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Edit()
        {
            ViewData["Title"] = "SkillProfi - Редактирование";

            var model = new SiteConfigViewModel(Config.Instance);

			return View(model);
		}

		[HttpPost]
        [Authorize]
		public IActionResult Edit(SiteConfigViewModel config)
		{
            var siteConfig = Config.Instance;
			siteConfig.Motto = config.Motto;
			siteConfig.HeroTitle = config.HeroTitle;
            siteConfig.HeroBtnToSend = config.HeroBtnToSend;
            siteConfig.HeroSecondTitle = config.HeroSecondTitle;
            siteConfig.Save();

			return RedirectToAction("Index");
		}
	}
}

SkillProfi.Web/Views/Hero/Edit.cshtml
@model SiteConfigViewModel

<section class="section edit__hero">
	<form method="post" asp-action="Edit">
		<dl>
			<dt>Девиз</dt>
			<dd>
				<input class="hero__edit__input" type="text" asp-for="@Model.Motto" placeholder="@Model.Motto" />
			</dd>
			<dt>Заголовок на баннере</dt>
			<dd>
				<input class="hero__edit__input" type="text" asp-for="@Model.HeroTitle" placeholder="@Model.HeroTitle" />
			</dd>
			<dt>Надпись кнопки на баннере</dt>
			<dd>
				<input class="hero__edit__input" type="text" asp-for="@Model.HeroBtnToSend" placeholder="@Model.HeroBtnToSend" />
			</dd>
			<dt>Заголовок формы подачи заявки</dt>
			<dd>
				<input class="hero__edit__input" type="text" asp-for="@Model.HeroSecondTitle" placeholder="@Model.HeroSecondTitle" />
			</dd>
			
			<button class="btn btn__reset" type="submit">Изменить</button>
		</dl>
	</form>
</section>

SkillProfi.Web/Views/Hero/Index.cshtml
@model Request
@{
    ViewData["Title"] = "SkillProfi";
}

<section class="section hero">
    <div class="container container__hero">
        <h1 class="hero__title">@Config.Instance.HeroTitle</h1>

        <button class="btn btn__reset hero__btn">@Config.Instance.HeroBtnToSend</button>
    </div>
</section>

@if (User.Identity.IsAuthenticated)
{
    <section class="section">
        <div class="container">
            <a href="#" class="inquiry__link">Главная</a>

            <h2 class="inquiry__title">@Config.Instance.HeroSecondTitle</h2>

            <form class="form flex" asp-action="Index" method="post">
                <div style="color: #ff0000" asp-validation-summary="ModelOnly"></div>
                <div class="form-top flex">
                    <div class="form__name flex">
                        <label asp-for="Name" class="label__name">
                            Имя
                        </label>
                        <input type="text" name="name" asp-for="Name" id="name" class="input__name"
                               placeholder="Козлов Иван Петрович" required>
                    </div>

                    <div class="form__email flex">
                        <label asp-for="Email" class="label__email">
                            Email
                        </label>
                        <input type="email" name="email" asp-for="Email" id="email" class="input__email"
                               placeholder="example@gmail.com" required>
                    </div>
                </div>

                <div class="form-bottom flex">
                    <label asp-for="Message">Текст сообщения</label>
                    <textarea class="message" name="message" asp-for="Message" id="message"
                              cols="30" rows="10" required></textarea>
                </div>

                <button class="btn btn__reset form__btn" type="submit">Отправить</button>
            </form>
        </div>
    </section>

    <div class="block__btn__edit">
        <a class="btn btn__reset btn__hero__edit" asp-action="Edit">Редактировать</a>
    </div>
}
else
{
    <section class="section inquiry">
        <div class="container">
            <a href="#" class="inquiry__link">Главная</a>

            <h2 class="inquiry__title">@Config.Instance.HeroSecondTitle</h2>

            <form class="form flex" asp-action="Index" method="post">
                <div class="form-top flex">
                    <div class="form__name flex">
                        <label asp-for="Name" class="label__name">
                            Имя
                        </label>
                        <input type="text" name="name" asp-for="Name" id="name" class="input__name"
                               placeholder="Козлов Иван Петрович" required>
                    </div>

                    <div class="form__email flex">
                        <label asp-for="Email" class="label__email">
                            Email
                        </label>
                        <input type="email" name="email" asp-for="Email" id="email" class="input__email"
                               placeholder="example@gmail.com" required>
                    </div>
                </div>

                <div class="form-bottom flex">
                    <label asp-for="Message">Текст сообщения</label>
                    <textarea class="message" name="message" asp-for="Message" id="message"
                              cols="30" rows="10" required></textarea>
                </div>

                <button class="btn btn__reset form__btn" type="submit">Отправить</button>
            </form>
        </div>
    </section>
}

SkillProfi.Web/Views/Hero/RequestSent.cshtml
@model string
@{
    ViewData["Title"] = "SkillProfi";
}

<h2>@Model</h2>

<div class="flex blog__btn__back">
    <a class="btn btn__reset blog__btn" asp-controller="Hero" asp-action="Index">Назад</a>
</div>