SkillProfi.Web/ViewModels/BlogViewModel.cs
using SkillProfi.DAL.Models;

namespace SkillProfi.Web.ViewModels
{
    public class BlogViewModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string ShortDescription { get; set; }

        public DateTime Created { get; set; }

        public string ImageUrl { get; set; }

        public IFormFile File { get; set; }



        public BlogViewModel() { }

        public BlogViewModel(Blog blog)
        {
            this.Id = blog.Id;
            this.Title = blog.Title;
            this.Description = blog.Description;
            this.ShortDescription = blog.ShortDescription;
            this.Created = blog.Created;
            this.ImageUrl = blog.ImageUrl;
        }
    }
}

SkillProfi.Web/Controllers/BlogsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.VisualBasic;
using SkillProfi.DAL.Models;
using SkillProfi.Web.Interfaces;
using SkillProfi.Web.ViewModels;

namespace SkillProfi.Web.Controllers
{
    public class BlogsController : Controller
    {
        private IData<Blog> _data;
        private IWebHostEnvironment _appEnvironment;

        public BlogsController(IData<Blog> data, IWebHostEnvironment appEnvironment)
        {
            _data = data;
            _appEnvironment = appEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = "SkillProfi - Блог";

            return View(await _data.GetAll());
        }

        [HttpGet("Blogs/{id}")]
        public async Task<IActionResult> Details(int? id)
        {
            var blog = await _data.GetById(id);
            ViewData["Title"] = $"SKillProfi - Блог - {blog.Title}";

            return View(blog);
        }

        [Authorize]
        [HttpGet("Blogs/Create")]
        public IActionResult Create()
        {
            ViewData["Title"] = $"SKillProfi - Блог - Добавление";

            var blogViewModel = new BlogViewModel();

            return View(blogViewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(BlogViewModel blogViewModel)
        {
            var uploadedFile = blogViewModel.File;
            string pathFile;

            if (uploadedFile != null)
            {
                // путь к папке img
                pathFile = "/img/" + Guid.NewGuid() + "." + uploadedFile.FileName.Split('.')[^1];
                var fullPath = _appEnvironment.WebRootPath + pathFile;
                // сохраняем файл в папку img в каталоге wwwroot
                using (var fileStream = new FileStream(fullPath, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                }
            }
            else
            {
                pathFile = "/img/default.jpg";
            }

            await _data.Add(new Blog
            {
                Title = blogViewModel.Title,
                Description = blogViewModel.Description,
                ShortDescription = blogViewModel.ShortDescription,
                Created = DateTime.Now,
                ImageUrl = $".{pathFile}"
            });

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet("Blogs/Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["Title"] = $"SKillProfi - Блог - Изменение";

            var blogViewModel = new BlogViewModel(await _data.GetById(id));

            return View(blogViewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(BlogViewModel blogViewModel)
        {
            var uploadedFile = blogViewModel.File;
            string? pathFile;
            if (uploadedFile != null)
            {
                // путь к папке img
                pathFile = "/img/" + Guid.NewGuid() + "." + uploadedFile.FileName.Split('.')[^1];
                // сохраняем файл в папку img в каталоге wwwroot
                using (var fileStream = new FileStream(_appEnvironment.WebRootPath + pathFile, FileMode.Create))
                {
                    await uploadedFile.CopyToAsync(fileStream);
                    if (!blogViewModel.ImageUrl.Contains("/default.jpg"))
                    {
                        var path = _appEnvironment.WebRootPath + blogViewModel.ImageUrl;
                        System.IO.File.Delete(path);
                    }
                }
            }
            else
            {
                pathFile = blogViewModel.ImageUrl.Remove(0, 1);
            }

            await _data.Update(new Blog
            {
                Id = blogViewModel.Id,
                Title = blogViewModel.Title,
                Created = DateTime.Now,
                Description = blogViewModel.Description,
                ShortDescription = blogViewModel.ShortDescription,
                ImageUrl = $".{pathFile}"
            });

            return RedirectToAction("Index");
        }


        [Authorize]
        [HttpGet("Blogs/Delete/{id}")]
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["Title"] = $"SKillProfi - Блог - Удаление";

            return View(await _data.GetById(id));
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(Blog blog)
        {
            await _data.Delete(blog.Id);

            if (!blog.ImageUrl.Contains("/default.jpg"))
            {
                var path = _appEnvironment.WebRootPath + blog.ImageUrl;
                System.IO.File.Delete(path);
            }

            return RedirectToAction("Index");
        }
    }
}

SkillProfi.Web/Views/Blogs/Create.cshtml
@model SkillProfi.Web.ViewModels.BlogViewModel
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<h4>Проект</h4>
<hr />
<section class="section blog">
    <form method="post" asp-action="Create" enctype="multipart/form-data">
        <input asp-for="@Model.Id" hidden />
        <div class="blog__create">
            <div class="upload">
                <div class="form-group">
                    <label class="label">
                        <i class="material-icons">attach_file</i>
                        <span class="title">Добавить файл</span>
                        <input asp-for="@Model.File" type="file" accept=".png,.jpg,.jpeg" id="file">
                    </label>
                    <div class="upload__img__preview">
                        <span id="output" class="img__preview"></span>
                    </div>
                </div>
            </div>
            <div>
                <dl class="attrs">
                    <dt>
                        Название блога
                    </dt>
                    <dd>
                        <input class="form__project__title" asp-for="@Model.Title" required maxlength="50" />
                    </dd>
                    <dt>
                        Короткое писание блога (ограничение 220 символов)
                    </dt>
                    <dd>
                        <textarea class="textarea__shortdescr" asp-for="@Model.ShortDescription" 
                        maxlength="220" required></textarea>
                    </dd>
                    <dt>
                        Полное описание блога
                    </dt>
                    <dd>
                        <textarea class="textarea__descr" asp-for="@Model.Description" required></textarea>
                    </dd>
                </dl>
            </div>
        </div>
        <div>
            <button class="r__btn request__edit btn btn__reset" type="submit">
                Добавить
            </button>
            <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
        </div>
    </form>
</section>

<script>
    function handleFileSelect(evt) {
        var file = evt.target.files; // FileList object
        var f = file[0];
        // Only process image files.
        if (!f.type.match('image.*')) {
            alert("Image only please....");
        }
        var reader = new FileReader();
        // Closure to capture the file information.
        reader.onload = (function (theFile) {
            return function (e) {
                var label = document.querySelector('.label')
                label.style.display = 'none'
                // Render thumbnail.
                var span = document.createElement('span');
                span.innerHTML = ['<img class="thumb" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
                document.getElementById('output').insertBefore(span, null);
            };
        })(f);
        // Read in the image file as a data URL.
        reader.readAsDataURL(f);
    }
    document.getElementById('file').addEventListener('change', handleFileSelect, false);
</script>

SkillProfi.Web/Views/Blogs/Delete.cshtml
@model Blog

<section class="section blog">    
    <form method="post" asp-action="Delete">
        <input asp-for="@Model.Id" hidden />
        <input asp-for="@Model.ImageUrl" hidden />

        <div class="blog__head flex">
            <h1>
                @Model.Title
            </h1>

            <img class="blog__img" src="@Model.ImageUrl.Remove(0, 1)" />
        </div>

        <div class="blog__description">
            @Html.Raw(Model.Description.Replace("\n", "<br>"))
        </div>

        <div>
            <button class="r__btn request__edit btn btn__reset" type="submit">
                Удалить
            </button>
            <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
        </div>
    </form>
</section>

SkillProfi.Web/Views/Blogs/Details.cshtml
@model Blog

<section class="section blog" >
    <h1 class="blog__title">
        @Model.Title
    </h1>

    <p class="blogs__item__data">@Model.Created.ToString("dd.MMMM.yyyy")</p>

    <div class="blog__descr flex">
        <img class="blogs__item__img blog__img" src=".@Model.ImageUrl" />

        <p class="blog__descr">
            @Html.Raw(Model.Description.Replace("\n", "<br>"))
        </p>
    </div>

    <div class="flex blog__btn__back">
        <a class="btn btn__reset blog__btn" asp-controller="Blogs" asp-action="Index">Назад</a>
    </div>
</section>

SkillProfi.Web/Views/Blogs/Edit.cshtml
@model SkillProfi.Web.ViewModels.BlogViewModel
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

<h4>Проект</h4>
<hr />
<section class="section blog">
    <form method="post" asp-action="Edit" enctype="multipart/form-data">
        <input asp-for="@Model.Id" hidden />
        <input asp-for="@Model.ImageUrl" hidden />
        <div class="blog__create">
            <div class="upload">
                <img class="form-group" src="@Model.ImageUrl.Remove(0, 1)" />
                <p>Изменить картинку</p>
                <div class="form-group">
                    <label class="label">
                        <i class="material-icons">attach_file</i>
                        <span class="title">Добавить файл</span>
                        <input asp-for="@Model.File" type="file" accept=".png,.jpg,.jpeg" id="file">
                    </label>
                    <div class="upload__img__preview">
                        <span id="output" class="img__preview"></span>
                    </div>
                </div>
            </div>
            <div>
                <dl class="attrs">
                    <dt>
                        Название блога
                    </dt>
                    <dd>
                        <input class="form__project__title" asp-for="@Model.Title" required maxlength="50" />
                    </dd>
                    <dt>
                        Короткое писание блога (ограничение 220 символов)
                    </dt>
                    <dd>
                        <textarea class="textarea__shortdescr" asp-for="@Model.ShortDescription"
                                  maxlength="220" required></textarea>
                    </dd>
                    <dt>
                        Полное описание блога
                    </dt>
                    <dd>
                        <textarea class="textarea__descr" asp-for="@Model.Description" required></textarea>
                    </dd>
                </dl>
            </div>
        </div>
        <div>
            <button class="r__btn request__edit btn btn__reset" type="submit">
                Изменить
            </button>
            <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
        </div>
    </form>
</section>

<script>
    function handleFileSelect(evt) {
        var file = evt.target.files; // FileList object
        var f = file[0];
        // Only process image files.
        if (!f.type.match('image.*')) {
            alert("Image only please....");
        }
        var reader = new FileReader();
        // Closure to capture the file information.
        reader.onload = (function (theFile) {
            return function (e) {
                var label = document.querySelector('.label')
                label.style.display = 'none'
                // Render thumbnail.
                var span = document.createElement('span');
                span.innerHTML = ['<img class="thumb" title="', escape(theFile.name), '" src="', e.target.result, '" />'].join('');
                document.getElementById('output').insertBefore(span, null);
            };
        })(f);
        // Read in the image file as a data URL.
        reader.readAsDataURL(f);
    }
    document.getElementById('file').addEventListener('change', handleFileSelect, false);
</script>

SkillProfi.Web/Views/Blogs/Index.cshtml
@model IEnumerable<Blog>

<section class="section blogs">
    <h1 class="blogs__title">Блог</h1>

    <ul class="blogs__list list__reset flex">
        @foreach(Blog blog in Model)
        {
            <li class="blogs__item">
                <a class="flex blogs__item__link" asp-action="Details" asp-route-id="@blog.Id">
                    <p class="blogs__item__data">@blog.Created.ToString("dd.MMMM.yyyy")</p>

                    <img class="blogs__item__img" src="@blog.ImageUrl" />

                    <p class="blogs__item__title">@blog.Title</p>

                    <p class="blogs__item__shortdescr">
                        @blog.ShortDescription
                    </p>
                </a>

                @if (User.Identity.IsAuthenticated)
                {
                    <div class="blogs__ico">
                        <a asp-controller="Blogs" asp-action="Edit" asp-route-id="@blog.Id">
                            <img class="blogs__ico__edit" src="~/img/ico-edit.png" />
                        </a>
                        <a asp-controller="Blogs" asp-action="Delete" asp-route-id="@blog.Id">
                            <img class="blogs__ico__del" src="~/img/ico-del.png" />
                        </a>
                    </div>
                }
            </li>
        }
    </ul>

    @if (User.Identity.IsAuthenticated)
    {
        <div class="blogs__btn__add">
            <a class="btn btn__reset r__btn" asp-controller="Blogs" asp-action="Create">Добавить блог</a>
        </div>
    }
</section>