SkillProfi.Web/Controllers/ServicesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SkillProfi.DAL.Models;
using SkillProfi.Web.Interfaces;

namespace SkillProfi.Web.Controllers
{
    public class ServicesController : Controller
    {
        private IData<Service> _data;

        public ServicesController(IData<Service> data)
        {
            _data = data;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            ViewData["Title"] = "SkillProfi - Услуги";

            var services = await _data.GetAll();

            return View(services);
        }

        [Authorize]
        [HttpGet("Services/Edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            ViewData["Title"] = "SkillProfi - Услуги - Редактирование";

            var service = await _data.GetById(id);

            return View(service);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(Service service)
        {
            await _data.Update(service);

            return RedirectToAction("Index");
        }

        [Authorize]
        [HttpGet("Services/Delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            ViewData["Title"] = "SkillProfi - Услуги - Удаление";

            var service = await _data.GetById(id);

            return View(service);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Delete(Service service)
        {
            await _data.Delete(service.Id);

            return RedirectToAction("Index");
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewData["Title"] = "SkillProfi - Услуги - Добавление";

            var service = new Service();

            return View(service);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Service service)
        {
            await _data.Add(service);

            return RedirectToAction("Index");
        }
    }
}

SkillProfi.Web/Views/Services/Create.cshtml
@model SkillProfi.DAL.Models.Service

<h4>Услуга</h4>
<hr />
<section class="section service">
    <form method="post" asp-action="Create">
        <input asp-for="@Model.Id" hidden />
        <div>
            <dl class="attrs">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd>
                    <input asp-for="@Model.Title" required />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    <textarea class="textarea__descr" asp-for="@Model.Description" required></textarea>
                </dd>
            </dl>
        </div>
        <div>
            <button class="r__btn request__edit btn btn__reset" type="submit">
                Добавить
            </button>
            <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
        </div>
    </form>
</section>

SkillProfi.Web/Views/Services/Delete.cshtml
@model SkillProfi.DAL.Models.Service

<h4>Услуга</h4>
<hr />
<section class="section service">
    <form method="post" asp-action="Delete">
        <input asp-for="@Model.Id" hidden />
        <div>
            <dl class="attrs">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Title)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
        <div>
            <button class="r__btn request__edit btn btn__reset" type="submit">
                Удалить
            </button>
            <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
        </div>
    </form>
</section>

SkillProfi.Web/Views/Services/Edit.cshtml
@model SkillProfi.DAL.Models.Service

<h4>Услуга</h4>
<hr />
<section class="section service">
    <form method="post" asp-action="Edit">
        <input asp-for="@Model.Id" hidden />
        <div>
            <dl class="attrs">
                <dt>
                    @Html.DisplayNameFor(model => model.Title)
                </dt>
                <dd>
                    <input asp-for="@Model.Title" required />
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd>
                    <textarea class="textarea__descr" asp-for="@Model.Description" required></textarea>
                </dd>
            </dl>
        </div>
        <div>
            <button class="r__btn request__edit btn btn__reset" type="submit">
                Изменить
            </button>
            <a class="r__btn request__back btn btn__reset" asp-action="Index">Назад</a>
        </div>
    </form>
</section>

SkillProfi.Web/Views/Services/Index.cshtml
@model IEnumerable<Service>
@{
    int i = 1;
}

<section class="section services">
    <h1 class="services__title">Что мы можем?</h1>

    <div class="acor-container">

        @foreach(Service service in Model)
        {
            if (i == 1)
            {
                <input type="radio" name="acor" id="acor@(i)" checked="checked" />
            }
            else
            {
                <input type="radio" name="acor" id="acor@(i)" />
            }
            <label for="acor@(i++)" )" class="services__label__title">
                @service.Title
                @if (User.Identity.IsAuthenticated)
                {
                    <div class="services__ico">
                        <a asp-controller="Services" asp-action="Edit" asp-route-id="@service.Id">
                            <img class="services__ico__edit" src="~/img/ico-edit.png" />
                        </a>
                        <a asp-controller="Services" asp-action="Delete" asp-route-id="@service.Id">
                            <img class="services__ico__del" src="~/img/ico-del.png" />
                        </a>
                    </div>
                }
            </label>
            <div class="acor-body">
                <p>@service.Description</p>
            </div>
        }
    </div>

    @if (User.Identity.IsAuthenticated)
    {
        <div>
            <a class="r__btn btn btn__reset" asp-action="Create">Добавить услугу</a>
        </div>
    }
</section>